FROM ubuntu:latest
RUN apt update && apt upgrade -y && apt install -y python && apt install -y python-pip \
&& pip install websockets
ENV DEBIAN_FRONTEND=noninteractive
COPY ./server.py /
CMD ["python3", "/server.py"]
EXPOSE 5678

